baseURL: / 
languageCode: pt-br
defaultContentLanguage: pt
title: Periódicos em Nuvens
theme: cayman-hugo-theme

# Google analytics
googleAnalytics: UA-123456789-1

# Disqus comments
disqusShortname: yourdiscussshortname

# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

params:
  # Header text, can be markdown
  project_name: Periódicos em Nuvens
  project_tagline: Soluções para revistas acadêmicas em SEER / OJS

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 01-02-2006

  # Footer text, can be markdown
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [CloudFlare](https://dash.cloudflare.com/).

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex: true

  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#159957"
  header_background_color_secondary: "#155799"

  # Text colors
  section_headings_color: "#159957"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"

menu:
  nav:
    - name: Periódicos em nuvens
      url: /
      weight: 1
    - name: O que é
      url: /o-que-e/
      weight: 2
    - name: Quem utiliza
      url: /clientes/
      weight: 3
    - name: Planos
      url: /planos/
      weight: 4
    - name: Serviços
      url: /servicos/
      weight: 5
    - name: Solicitar Orçamento
      url: /solicitar-orcamento/
      weight: 6
    - name: Contratar
      url: /contratar/
      weight: 7
    - name: Perguntas Frequentes
      url: /faq/
      weight: 8
    - name: Quem Somos
      url: /quem-somos/
      weight: 9
    - name: Contato
      url: /contato/
      weight: 10   


